//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaLocator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediaLocator_MediaFilesContainer : DbContext
    {
        public MediaLocator_MediaFilesContainer()
            : base("name=MediaLocator_MediaFilesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audio> AudioSet { get; set; }
        public virtual DbSet<Video> VideoSet { get; set; }
        public virtual DbSet<Picture> PictureSet { get; set; }
        public virtual DbSet<Folder> FolderSet { get; set; }
        public virtual DbSet<Playlist> PlaylistSet { get; set; }
    }
}
