//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaLocator
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Video
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public long Size { get; set; }
        public long Long { get; set; }
        public System.DateTime SaveDate { get; set; }
    
        public virtual Folder Folder { get; set; }
    }
}
